In [16]:
from sklearn.metrics import r2_score
y_true=[0,4,2.5,7]
y_pred=[0.5,5,2,7]
print(r2_score(y_true,y_pred))

0.9416058394160584


In [18]:
import numpy as np
from sklearn.metrics import mean_squared_error
y_true=[0,4,2.5,7]
y_pred=[0.5,5,2,7]
print('MSE: ', mean_squared_error(y_true,y_pred))
print('RMSE: ', np.sqrt(mean_squared_error(y_true,y_pred)))

MSE:  0.375
RMSE:  0.6123724356957945


In [19]:
from sklearn.metrics import mean_absolute_error
y_true=[0,4,2.5,7]
y_pred=[0.5,5,2,7]
print('MAE: ', mean_absolute_error(y_true,y_pred))

MAE:  0.5


In [21]:
from sklearn.metrics import accuracy_score
y_true=[0,4,2,7]
y_pred=[0,5,2,7]
print(accuracy_score(y_true,y_pred))

0.75


In [23]:
from sklearn.metrics import confusion_matrix
y_true=[0,1,2,1,0]
y_pred=[0,1,2,2,1]
print(confusion_matrix(y_true,y_pred))

[[1 1 0]
 [0 1 1]
 [0 0 1]]


In [27]:
from sklearn.metrics import precision_score,recall_score,f1_score
y_true=[0,1,2,1,0]
y_pred=[0,1,2,2,1]
print(precision_score(y_true,y_pred,average=None))
print(recall_score(y_true,y_pred,average=None))
print(f1_score(y_true,y_pred,average=None))

[1.  0.5 0.5]
[0.5 0.5 1. ]
[0.66666667 0.5        0.66666667]


In [28]:
from sklearn.metrics import classification_report
y_true=[0,4,2,7]
y_pred=[0,5,2,7]
print(classification_report(y_true,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         1
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         0
           7       1.00      1.00      1.00         1

    accuracy                           0.75         4
   macro avg       0.60      0.60      0.60         4
weighted avg       0.75      0.75      0.75         4



D:\Program Files\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Program Files\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Program Files\Python310\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\Program Files\Python310\lib\site-packages\sklearn\metr