In [1]:
import numpy as np

In [2]:
arr=np.array([[1,2],
           [3,4]])

In [3]:
arr

array([[1, 2],
       [3, 4]])

In [4]:
np.tile(arr,4)

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4]])

In [5]:
arr2=np.array([4,7,2,6,3])

In [6]:
arr2

array([4, 7, 2, 6, 3])

In [7]:
np.argsort(arr2)

array([2, 4, 0, 3, 1], dtype=int64)